using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace KeplerEngine.Graphics;

public class ParticleData
{
    /// <summary>
    /// This is auto-generated by the particle manager
    /// </summary>
    public uint ID { get; internal set; }

    public Texture2D Texture { get; set; }

    public Rectangle SourceRectangle { get; set; } = new Rectangle();

    /// <summary>
    /// The total duration of the particle in milliseconds. 1000 ms = 1s.
    /// </summary>
    public double Duration { get; set; }

    /// <summary>
    /// The elapsed time in milliseconds since this particle being passed through the particle manager. 1000 ms = 1s.
    /// The particle manager removes this particle from their particles list when ElapsedTime is major than the total duration.
    /// </summary>
    public double ElapsedTime { get; set; }

    /// <summary>
    /// The blend color while drawing this particle through the particle manager.
    /// </summary>
    public Color Color { get; set; }

    public Vector2 Position { get; set; }

    public float Rotation { get; set; }

    public Vector2 Gravity { get; set; }

    public Vector2 Scale { get; set; }

    public SpriteEffects Effects { get; set; } = SpriteEffects.None;

    /// <summary>
    /// This fixes undesired effects while rendering a particle over another one.
    /// </summary>
    public float LayerDepth { get; set; }
}